name: enigma_web
description: Attempt to create unified API to control Enigma1 & Enigma2 web interfaces
version: 1.0.5
homepage: https://github.com/shaxxx/EnigmaWeb.Dart.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  logging: ^0.11.3+2
  dio: ">=3.0.0 <3.0.8"
  xml: ^3.5.0
  cookie_jar: ^1.0.1
  alt_http: ^0.3.0
  dio_cookie_manager: ^1.0.0
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.10.0
